name: tele_tudo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5
  shared_preferences: ^2.0.16   
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # firebase_core: ^10.1.1
  # firebase_messaging: ^20.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

